## Funciones de Python

In [ ]:
# La definición de la función
def positivos(numeros): 
    total = 0
    for numero in numeros: 
        if numero > 0:
            total+=1 
    return total

In [ ]:
 # Llamada a la función
print(positivos([23,45,21,-2,43,-45,-7, 9, 29]))

## Variables Globales

In [ ]:
# La definición de la función
def imprimir(numeros): 
    for numero in numeros:
        print(f"{numero} + {factor} = {numero+factor}") 
    return 

# Llamamos a la función usando la variable total ahora como una variable global # La definición de la función

factor = 3
print(imprimir([23,45,21,-2,43,-45,-7, 9, 29]))

## Devolviendo más de un valor

In [ ]:
def funcion(lista, x, y): 
    total_x, total_y = 0, 0 
    for elemento in lista:
        if elemento == x: total_x += 1
        if elemento == y: total_y += 1
    return total_x, total_y

In [ ]:
# Probamos la función
v_x, v_y= 2,6
t_x, t_y = funcion([2,4,2,5,3,5,2,6], v_x, v_y)
print(f"{v_x} aparece {t_x} veces y {v_y} aparece {t_y} veces")

## Argumentos con valores por defecto

In [ ]:
def funcion_x(lista, tipo = 2): 
    r=0
    for elemento in lista: 
        if tipo == 1:
            r -= elemento 
        elif tipo == 2:
            r += elemento
    return r
print(funcion_x([1,2,3,4]))
print(funcion_x([1,2,3,4], tipo = 1))

## Usando funciones del lenguaje

In [1]:
import numpy as np

lista = [2,4,2,5,3,5,2,6] 
np.mean(lista)

3.625

In [2]:
print(f"MAX = {np.max(lista)} - MIN = {np.min(lista)}")

MAX = 6 - MIN = 2


In [3]:
datos = [[1,2,3], [5,10,15], [4,6,8]] # Calcula el promedio por filas 
print(datos)
np.mean(datos, axis = 1)

[[1, 2, 3], [5, 10, 15], [4, 6, 8]]


array([ 2., 10.,  6.])

In [4]:
# Calcula el promedio por columnas
np.mean(datos, axis = 0)

array([3.33333333, 6.        , 8.66666667])

In [5]:
# Calcula el promedio de todos los datos
np.mean(datos)

6.0

In [6]:
datos[1][1]

10

In [7]:
type(datos)

list

In [8]:
df = np.array(datos)

In [9]:
type(df)

numpy.ndarray

In [10]:
df

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 4,  6,  8]])

In [11]:
df[1,1]

10

In [12]:
df[2,1:]

array([6, 8])

In [13]:
df2=df

In [14]:
df2

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 4,  6,  8]])

In [15]:
df[1,1]=100

In [16]:
df

array([[  1,   2,   3],
       [  5, 100,  15],
       [  4,   6,   8]])

In [17]:
df2

array([[  1,   2,   3],
       [  5, 100,  15],
       [  4,   6,   8]])

In [18]:
df = np.array(datos)

In [19]:
df

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 4,  6,  8]])

In [20]:
df2=np.array(df)

In [21]:
df2

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 4,  6,  8]])

In [22]:
df[1,1]=100

In [23]:
df

array([[  1,   2,   3],
       [  5, 100,  15],
       [  4,   6,   8]])

In [24]:
df2

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 4,  6,  8]])

In [25]:
df+df2

array([[  2,   4,   6],
       [ 10, 110,  30],
       [  8,  12,  16]])

In [26]:
df-df2

array([[ 0,  0,  0],
       [ 0, 90,  0],
       [ 0,  0,  0]])

In [27]:
df*df2

array([[   1,    4,    9],
       [  25, 1000,  225],
       [  16,   36,   64]])

In [28]:
df/df2

array([[ 1.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1.,  1.]])